name: Deploy FastAPI to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 1 : Authentification avec Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Étape 2 : Installer le SDK Google Cloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: premium-axis-450910-f6

      # Étape 3 : Vérifier l'authentification
      - name: Verify Authentication
        run: gcloud auth list

      # Étape 4 : Construire et déployer sur Cloud Run
      - name: Build and deploy to Google Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/premium-axis-450910-f6/fastapi-app
          gcloud run deploy fastapi-app --image gcr.io/premium-axis-450910-f6/fastapi-app --platform managed --region us-central1 --allow-unauthenticated
