name: Deploy FastAPI to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: YOUR_PROJECT_ID
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and deploy to Google Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/YOUR_PROJECT_ID/fastapi-app
          gcloud run deploy fastapi-app --image gcr.io/YOUR_PROJECT_ID/fastapi-app --platform managed --region us-central1 --allow-unauthenticated
